# Sample LoRA training config for Kohya_ss
# Copy this file and adjust paths/values as needed

# --- Core training settings ---
pretrained_model_name_or_path = "/workspace/models/base_model.safetensors"
output_dir = "/workspace/output"
output_name = "lora_sample"
save_model_as = "safetensors"
save_precision = "fp16"
mixed_precision = "fp16"

# --- Dataset ---
# This expects you to mount ./dataset:/workspace/dataset in docker-compose
dataset_config = "/workspace/configs/dataset_lora.toml"

# --- Training parameters ---
epoch = 1
train_batch_size = 1
learning_rate = 0.0001
unet_lr = 0.0001
gradient_accumulation_steps = 1
max_train_steps = 1600
max_grad_norm = 1

# --- Network ---
network_module = "networks.lora"
network_dim = 8
network_alpha = 1
network_train_unet_only = true

# --- Bucketing / resolution ---
enable_bucket = true
bucket_no_upscale = true
bucket_reso_steps = 64
resolution = "1024,1024"
min_bucket_reso = 256
max_bucket_reso = 2048

# --- Optimizer ---
optimizer_type = "AdamW8bit"
optimizer_args = []

# --- Logging / samples ---
logging_dir = "/workspace/output/logs"
sample_prompts = "/workspace/configs/sample_prompts.txt"
sample_sampler = "euler_a"
save_every_n_epochs = 1

# --- Misc ---
clip_skip = 1
prior_loss_weight = 1
loss_type = "l2"
xformers = true
